[package]
name = "basket"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["gossip", "agave-gossip"]

[workspace.dependencies]
basket-gossip = { path = "./gossip"}
solana-gossip = { path = "./agave-gossip"}